### ISSUE TITLE
Main Menu and Lobby

### ISSUE THREAD

**Issue by Technohacker** [GE-Community/ChaosJam#3]
Options:

1. Creating a server
2. Joining a server

**Comment by abhinav3967** [comment]
#### The main menu should consist:-
> Play = takes you to lobby
> Settings = opens a settings popup
> quit = quits the game

**Comment by abhinav3967** [comment]
lobby will  have 
> start server
> join server
> offline
> training

**Comment by abhinav3967** [comment]
completed menu and lobby commited and pushed to this repo
